// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rxkweutwoqvpcwvzpdkg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ4a3dldXR3b3F2cGN3dnpwZGtnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0NTg3MTUsImV4cCI6MjA3MjAzNDcxNX0.bO4Ro-xAttSn-WVdLihoYQbsyfMgWinatn8kxCfR_KM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});